"""initial schema

Revision ID: 81010c282037
Revises: 
Create Date: 2026-03-31 02:07:43.692611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81010c282037'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_kind', sa.String(length=50), nullable=False),
    sa.Column('input_profile', sa.String(length=80), nullable=True),
    sa.Column('input_sizes', sa.JSON(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complexity_estimates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=True),
    sa.Column('metric_name', sa.String(length=80), nullable=False),
    sa.Column('estimated_class', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('alternatives', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complexity_estimates_experiment_id'), 'complexity_estimates', ['experiment_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('input_size', sa.Integer(), nullable=False),
    sa.Column('repetition_index', sa.Integer(), nullable=False),
    sa.Column('input_profile', sa.String(length=80), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('backend', sa.String(length=50), nullable=True),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.Column('truncated_stdout', sa.Boolean(), nullable=False),
    sa.Column('truncated_stderr', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_runs_experiment_id'), 'experiment_runs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_input_size'), 'experiment_runs', ['input_size'], unique=False)
    op.create_table('function_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_run_id', sa.String(length=36), nullable=False),
    sa.Column('function_name', sa.String(length=160), nullable=False),
    sa.Column('qualified_name', sa.String(length=255), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('total_time_ms', sa.Float(), nullable=False),
    sa.Column('self_time_ms', sa.Float(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('is_recursive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_metrics_experiment_run_id'), 'function_metrics', ['experiment_run_id'], unique=False)
    op.create_index(op.f('ix_function_metrics_function_name'), 'function_metrics', ['function_name'], unique=False)
    op.create_table('line_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_run_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('execution_count', sa.Integer(), nullable=False),
    sa.Column('total_time_ms', sa.Float(), nullable=False),
    sa.Column('percentage_of_total', sa.Float(), nullable=False),
    sa.Column('nesting_depth', sa.Integer(), nullable=False),
    sa.Column('loop_iterations', sa.Integer(), nullable=False),
    sa.Column('branch_visits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_metrics_experiment_run_id'), 'line_metrics', ['experiment_run_id'], unique=False)
    op.create_index(op.f('ix_line_metrics_line_number'), 'line_metrics', ['line_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_metrics_line_number'), table_name='line_metrics')
    op.drop_index(op.f('ix_line_metrics_experiment_run_id'), table_name='line_metrics')
    op.drop_table('line_metrics')
    op.drop_index(op.f('ix_function_metrics_function_name'), table_name='function_metrics')
    op.drop_index(op.f('ix_function_metrics_experiment_run_id'), table_name='function_metrics')
    op.drop_table('function_metrics')
    op.drop_index(op.f('ix_experiment_runs_input_size'), table_name='experiment_runs')
    op.drop_index(op.f('ix_experiment_runs_experiment_id'), table_name='experiment_runs')
    op.drop_table('experiment_runs')
    op.drop_index(op.f('ix_complexity_estimates_experiment_id'), table_name='complexity_estimates')
    op.drop_table('complexity_estimates')
    op.drop_table('experiments')
    # ### end Alembic commands ###
